name: Build and Deploy to Cloud Run

on:
  push:
    branches: ['main', 'develop']

env:
  PROJECT_ID: rich-torus-428117-m8
  GAR_LOCATION: us-east1
  REGION: us-east1

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Environment and Image Tag
        id: set-env
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "SERVICE=lolo-frontend-prod" >> $GITHUB_ENV
            echo "IMAGE_TAG=latest" >> $GITHUB_ENV
          elif [ "${{ github.ref }}" == "refs/heads/develop" ]; then
            echo "SERVICE=lolo-frontend-dev" >> $GITHUB_ENV
            echo "IMAGE_TAG=develop" >> $GITHUB_ENV
          else
            echo "SERVICE=lolo-frontend-cicd" >> $GITHUB_ENV
            echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV
          fi

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v1
        with:
          token_format: 'access_token'
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
          service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}'

      - name: Print Access Token (Debugging)
        run: echo "${{ steps.auth.outputs.access_token }}"

      - name: Docker Auth
        id: docker-auth
        uses: docker/login-action@v2
        with:
          username: 'oauth2accesstoken'
          password: ${{ steps.auth.outputs.access_token }}
          registry: ${{ env.REGION }}-docker.pkg.dev

      - name: Build and Push Container
        run: |
          IMAGE_NAME="${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}/lolo-frontend:${{ env.IMAGE_TAG }}"
          echo "Building Docker image with name: ${IMAGE_NAME}"
          docker build -f Dockerfile.dev -t "${IMAGE_NAME}" ./
          echo "Pushing Docker image: ${IMAGE_NAME}"
          docker push "${IMAGE_NAME}"

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          image: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}/lolo-frontend:${{ env.IMAGE_TAG }}

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
